# Decision Tree

Decision Tree is one of the most powerful and popular algorithm. Decision-tree algorithm falls under the category of supervised learning algorithms. It works for both continuous as well as categorical output variables.

![](https://www.saedsayad.com/images/Decision_Tree_1.png)

### Entropy

Entropy 		
A decision tree is built top-down from a root node and involves partitioning the data into subsets that contain instances with similar values (homogenous). ID3 algorithm uses entropy to calculate the homogeneity of a sample. If the sample is completely homogeneous the entropy is zero and if the sample is an equally divided it has entropy of one.

![](https://www.saedsayad.com/images/Entropy.png)

a) Entropy using the frequency table of one attribute:

![](https://www.saedsayad.com/images/Entropy_3.png)

b) Entropy using the frequency table of two attributes:

![](https://www.saedsayad.com/images/Entropy_2.png)

### Information Gain 		
The information gain is based on the decrease in entropy after a dataset is split on an attribute. Constructing a decision tree is all about finding attribute that returns the highest information gain (i.e., the most homogeneous branches).

Step 1: Calculate entropy of the target.

![](https://www.saedsayad.com/images/Entropy_target.png)

Step 2: The dataset is then split on the different attributes. The entropy for each branch is calculated. Then it is added proportionally, to get total entropy for the split. The resulting entropy is subtracted from the entropy before the split. The result is the Information Gain, or decrease in entropy. 

![](https://www.saedsayad.com/images/Entropy_attributes.png)

![](https://www.saedsayad.com/images/Entropy_gain.png)

Step 3: Choose attribute with the largest information gain as the decision node, divide the dataset by its branches and repeat the same process on every branch.

Step 4a: A branch with entropy of 0 is a leaf node.

![](https://www.saedsayad.com/images/Entropy_overcast.png)

In [ ]:
Step 4b: A branch with entropy more than 0 needs further splitting.

![](https://www.saedsayad.com/images/Entropy_Sunny.png)

In [ ]:
### Decision Tree to Decision Rules
		
A decision tree can easily be transformed to a set of rules by mapping from the root node to the leaf nodes one by one.

![](https://www.saedsayad.com/images/Decision_rules.png)

### Scikit Learn Approach for Decision Tree Classifier

In [13]:
from sklearn import tree
X = [[1, 0], [4, 2],[9,7]]
y = [4,1,2]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)
print(clf)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [14]:
print(clf.decision_path(X, check_input=True))

  (0, 0)	1
  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (1, 3)	1
  (2, 0)	1
  (2, 2)	1
  (2, 4)	1


In [15]:
clf.predict_proba([[5.3,0]], check_input=True)

array([[1., 0., 0.]])

In [16]:
print(clf.predict([[5.3,0]]))

[1]


In [17]:
print(clf.score(X,y))

1.0


### Python Implementation

#### Decision Tree Algorithm Pseudocode

    1. Place the best attribute of our dataset at the root of the tree.
    2. Split the training set into subsets. Subsets should be made in such a way that each subset contains data with the same value for an attribute.
    3. Repeat step 1 and step 2 on each subset until you find leaf nodes in all the branches of the tree.


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Import Dataset

In [9]:
link="/home/ashi/Desktop/program/python/webslitters/"
df = pd.read_excel(link+"diabetes.xlsx")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

##### Check Shape of Dataset

In [22]:
df.shape

(768, 9)

##### Drop the Outcome Data and Create the Predictor Set

In [24]:
X = df.drop(columns=["Outcome"])
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

##### Separate target values and Create Target Set

In [25]:
y = df["Outcome"].values
print(y[0:5])

[1 0 1 0 1]


##### Train Test Split Data

In [53]:
from sklearn.model_selection import train_test_split#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

##### [Train & Test Data Length](#####)

In [54]:
print("Length of Complete Dataset: ",len(df))
print("Length of Predictor Training Dataset: ",len(X_train),"(","%0.2f"%(len(X_train)/len(df)*100),"%)")
print("Length of Predictor Testing Dataset: ",len(X_test),"(","%0.2f"%(len(X_test)/len(df)*100),"%)")
print("Length of Target Training Dataset: ",len(y_train),"(","%0.2f"%(len(y_train)/len(df)*100),"%)")
print("Length of Target Testing Dataset: ",len(y_test),"(","%0.2f"%(len(y_test)/len(df)*100),"%)")

Length of Complete Dataset:  768
Length of Predictor Training Dataset:  537 ( 69.92 %)
Length of Predictor Testing Dataset:  231 ( 30.08 %)
Length of Target Training Dataset:  537 ( 69.92 %)
Length of Target Testing Dataset:  231 ( 30.08 %)


In [50]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
678            3      121             52              0        0  36.0   
53             8      176             90             34      300  33.7   
665            1      112             80             45      132  34.8   
219            5      112             66              0        0  37.8   
720            4       83             86             19        0  29.3   

     DiabetesPedigreeFunction  Age  
678                     0.127   25  
53                      0.467   58  
665                     0.217   24  
219                     0.261   41  
720                     0.317   34

#### Import Libraries

In [56]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

#### Create Decision Tree Classifier

In [57]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

#### Train Decision Tree Classifer

In [59]:
clf = clf.fit(X_train,y_train)
print(clf)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


#### Predict the response for test dataset

In [60]:
y_pred = clf.predict(X_test)
print(y_pred)

[0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 1 0 0
 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0
 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0]


#### Confusion Matrix

#### Score Calculation

In [67]:
print("Score by DecisionTreeClassifier: ",clf.score(X_test, y_test))
print("Accuracy by Matrics: ",metrics.accuracy_score(y_test, y_pred))

Score by DecisionTreeClassifier:  0.7012987012987013
Accuracy by Matrics:  0.7012987012987013


#### Confusion Matrix

In [72]:
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test,y_pred))

Confusion Matrix: 
 [[120  26]
 [ 43  42]]


#### Crosstab calculation for Original vs Predicted

##### Crosstab for Target

In [73]:
pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted    0   1  All
True                   
0          120  26  146
1           43  42   85
All        163  68  231

In [75]:
!pip install pydotplus

  Stored in directory: C:\Users\comp\AppData\Local\pip\Cache\wheels\35\7b\ab\66fb7b2ac1f6df87475b09dc48e707b6e0de80a6d8444e3628
Successfully built pydotplus


In [76]:
!pip install graphviz

#### export_graphviz function converts decision tree classifier into dot file and pydotplus convert this dot file to png or displayable form on Jupyter.

### Install graphviz from 
### https://graphviz.gitlab.io/_pages/Download/Download_windows.html

In [80]:
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

feature_cols=df.columns.tolist()[:-1]

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('diabetes.png')
Image(graph.create_png())

InvocationException: GraphViz's executables not found